[project]
name = "angelica"
version = "0.0.1"
description = "Agentic Labeling"
authors = []
requires-python = "==3.11.10"
readme = "README.md"
dependencies = [
    "aiohappyeyeballs==2.6.1",
    "aiohttp==3.13.5",
    "aiosignal==1.4.0",
    "annotated-doc==0.0.4",
    "annotated-types==0.7.0",
    "anyio==4.13.0",
    "attrs==26.1.0",
    "certifi==2026.4.22",
    "cfgv==3.5.0",
    "charset-normalizer==3.4.7",
    "clang==17.0.6",
    "cldk @ git+ssh://git@github.com/codellm-devkit/python-sdk.git@c77183a6a40503fb0d5b3be0523c48a5ecd91237",
    "click==8.3.2",
    "contourpy==1.3.3",
    "cycler==0.12.1",
    "dataclasses-json==0.6.7",
    "distlib==0.4.3",
    "distro==1.9.0",
    "et-xmlfile==2.0.0",
    "faiss-cpu==1.11.0",
    "filelock==3.25.2",
    "fonttools==4.62.1",
    "frozenlist==1.8.0",
    "greenlet==3.3.2",
    "h11==0.16.0",
    "hamster @ git+ssh://git@github.com/aster-test-generation/hamster.git@c3faa1f4018217cebddf3715c875f51874ea3b38",
    "httpcore==1.0.9",
    "httpx==0.28.1",
    "httpx-sse==0.4.3",
    "identify==2.6.19",
    "idna==3.13",
    "javalang==0.13.0",
    "Jinja2==3.1.6",
    "jiter==0.13.0",
    "joblib==1.4.2",
    "jsonpatch==1.33",
    "jsonpointer==3.1.1",
    "jsonschema==4.26.0",
    "jsonschema-specifications==2025.9.1",
    "kiwisolver==1.5.0",
    "langchain==0.3.26",
    "langchain-community==0.3.26",
    "langchain-core==0.3.83",
    "langchain-openai==0.3.30",
    "langchain-text-splitters==0.3.11",
    "langgraph==0.5.4",
    "langgraph-checkpoint==2.1.2",
    "langgraph-prebuilt==0.5.2",
    "langgraph-sdk==0.1.74",
    "langsmith==0.7.26",
    "libclang==17.0.6",
    "markdown-it-py==4.0.0",
    "MarkupSafe==3.0.3",
    "marshmallow==3.26.2",
    "matplotlib==3.10.8",
    "mdurl==0.1.2",
    "msgpack==1.1.2",
    "multidict==6.7.1",
    "mypy-extensions==1.1.0",
    "networkx==3.6.1",
    "nodeenv==1.10.0",
    "numpy==2.4.4",
    "openai==1.109.1",
    "openpyxl==3.1.5",
    "orjson==3.11.8",
    "ormsgpack==1.12.2",
    "packaging==25.0",
    "pandas==2.3.3",
    "pillow==12.2.0",
    "platformdirs==4.10.0",
    "pre-commit==4.6.0",
    "propcache==0.4.1",
    "protobuf==7.34.1",
    "pyarrow==20.0.0",
    "pydantic==2.13.3",
    "pydantic-core==2.46.3",
    "pydantic-settings==2.13.1",
    "Pygments==2.20.0",
    "pyparsing==3.3.2",
    "python-dateutil==2.9.0.post0",
    "python-discovery==1.4.2",
    "python-dotenv==1.2.2",
    "pytz==2026.1.post1",
    "PyYAML==6.0.3",
    "ray==2.54.1",
    "referencing==0.37.0",
    "regex==2026.4.4",
    "replicate==1.0.7",
    "repo==0.3.0",
    "requests==2.33.1",
    "requests-toolbelt==1.0.0",
    "rich==14.0.0",
    "rpds-py==0.30.0",
    "scikit-learn==1.8.0",
    "scipy==1.17.1",
    "seaborn==0.13.2",
    "shellingham==1.5.4",
    "six==1.17.0",
    "sniffio==1.3.1",
    "socksio==1.0.0",
    "SQLAlchemy==2.0.49",
    "tenacity==9.1.4",
    "threadpoolctl==3.6.0",
    "tiktoken==0.12.0",
    "toml==0.10.2",
    "tqdm==4.67.3",
    "tree-sitter==0.24.0",
    "tree-sitter-c==0.23.5",
    "tree-sitter-go==0.23.4",
    "tree-sitter-java==0.23.5",
    "tree-sitter-javascript==0.23.1",
    "tree-sitter-python==0.23.6",
    "typer==0.24.1",
    "typing-extensions==4.15.0",
    "typing-inspect==0.9.0",
    "typing-inspection==0.4.2",
    "tzdata==2026.1",
    "UpSetPlot==0.9.0",
    "urllib3==2.6.3",
    "uuid-utils==0.14.1",
    "virtualenv==21.5.1",
    "wget==3.2",
    "xxhash==3.6.0",
    "yarl==1.23.0",
    "zstandard==0.25.0",
]

[project.scripts]
angelica = "angelica.cli:app"

[tool.hatch.metadata]
allow-direct-references = true

[tool.hatch.build.targets.wheel]
packages = ["src/angelica", "src/coaster_label"]

[build-system]
requires = ["hatchling==1.27.0"]
build-backend = "hatchling.build"
